# Generated by Django 2.1.7 on 2023-03-06 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230306_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 6, 0, 36, 33, 200197)),
        ),
    ]
